image: node:14

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: test
  PORT: 3000

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run start &
    - sleep 120

deployJob:
  image: docker:19.03.12
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - docker pull node:14-bullseye
    - docker pull halverneus/static-file-server:latest
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker logout
    - docker rmi $IMAGE_TAG

